package com.example.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

enum class ObjectiveCategory(val label: String, val colorHex: String) {
    ACADEMIC("Academic Mastery", "#38E1FF"),
    FITNESS("Physical Transformation", "#00E676"),
    DISCIPLINE("Monk Discipline", "#FFB300"),
    HABIT("Core Habits", "#B388FF"),
    RESTORATION("Sleep & Recovery", "#70B8FF")
}

@Entity(tableName = "winter_arc_objectives")
data class WinterArcObjectiveEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val description: String = "",
    val category: ObjectiveCategory = ObjectiveCategory.ACADEMIC,
    val targetValue: String = "100%",
    val currentValue: String = "0%",
    val progressPercentage: Int = 0,
    val isCompleted: Boolean = false,
    val isAutoGenerated: Boolean = true,
    val orderIndex: Int = 0,
    val createdAtTimestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "winter_arc_goals_plan")
data class ArcGoalPlanItemEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val timeHorizon: String, // "DAILY", "WEEKLY", "MONTHLY"
    val title: String,
    val description: String = "",
    val targetDateOrPeriod: String = "",
    val isCompleted: Boolean = false,
    val xpReward: Int = 100,
    val priority: String = "HIGH", // "CRITICAL", "HIGH", "MEDIUM"
    val orderIndex: Int = 0
)
